dog/urls.py
from django.conf.urls import url
from dog import views


app_name = 'dog'
urlpatterns = [
    url(r'^add_region/$', views.add_region, name='add_region'),
    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.about, name='about'),
    url(r'^region/(?P<region_name_slug>[\w\-]+)/$', views.show_region, name='show_region'),
    url(r'^region/(?P<region_name_slug>[\w\-]+)/add_cottage/$', views.add_cottage, name='add_cottage'),
    url(r'^restricted/', views.restricted, name='restricted'),
    ]

dog_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from dog import views

urlpatterns = [
    
    # INDEX [HOME]
    url(r'^$', views.index, name='index'),
    
    # INCLUDE DOG APP URLS
    # [We have kept all of the urls in the app]
    url(r'^dog/', include('dog.urls')),
    
    # ADMIN SITE
    url(r'^admin/', admin.site.urls),
    # REGISTRATION
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^accounts/register/$', views.MyRegistrationView, name='registration_register'),
    ]

dog/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

class Region(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Region, self).save(*args, **kwargs)
    
    def __str__(self):
        return self.name

class Cottage(models.Model):
    region = models.ForeignKey(Region)
    title = models.CharField(max_length=128)
    address = models.CharField(max_length=128, blank=True)
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title

class UserProfile(models.Model):
    user = models.OneToOneField(User)
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

def __str__(self):
        return self.user.username

dog/forms.py
from django import forms
from dog.models import Cottage
from dog.models import Region
from dog.models import UserProfile
from django.contrib.auth.models import User 

class RegionForm(forms.ModelForm):
    name = forms.CharField(max_length=128, help_text="Please enter the region name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)
    class Meta:
        model = Region
        fields = ('name',)

class CottageForm(forms.ModelForm):
    title = forms.CharField(max_length=128, help_text="Please enter the name of the cottage.")
    address = forms.CharField(max_length=200, help_text="Please enter the address of the cottage.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    class Meta:
        model = Cottage
        exclude = ('region',)

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')

        if url and not url.startswith('http://'):
            url = 'http://' + url
            cleaned_data['url'] = url

            return cleaned_data

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')
        
class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website', 'picture')

dog/views.py
from registration.backends.simple.views import RegistrationView
from django.shortcuts import render_to_response
from django.shortcuts import render
from django.http import HttpResponse
from dog.models import Region
from dog.models import Cottage
from dog.forms import RegionForm
from dog.forms import CottageForm
from dog.forms import UserForm
from dog.forms import UserProfileForm
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from datetime import datetime
from django.template import RequestContext

def index(request):

   request.session.set_test_cookie()
   region_list = Region.objects.order_by('-likes')[:5]
   cottage_list = Cottage.objects.order_by('-views')[:5]
   context_dict = {'cottages':cottage_list, 'regions':region_list}

   visitor_cookie_handler(request)
   context_dict['visits'] = request.session['visits']

   print(request.session['visits'])
   
   response = render(request, 'dog/index.html', context=context_dict)
   return response

def about(request):
   context_dict = {}
   visitor_cookie_handler(request) 
   context_dict['visits'] = request.session['visits']
   return render(request, 'dog/about.html', context=context_dict)

def show_region(request, region_name_slug):
   context_dict = {}
   try:
      region = Region.objects.get(slug=region_name_slug)
      cottages = Cottage.objects.filter(region=region)
      context_dict['cottages'] = cottages
      context_dict['region'] = region
   except Region.DoesNotExist:
      context_dict['cottages'] = None
      context_dict['region'] = None
      
   return render(request, 'dog/region.html', context_dict)

def add_region(request):
   form = RegionForm()

   if request.method =='POST':
      form = RegionForm(request.POST)

      if form.is_valid():
         reg = form.save(commit=True)
         print(reg, reg.slug)
         
         return index(request)
   
      else: print(form.errors)
   return render(request, 'dog/add_region.html', {'form':form})


def add_cottage(request, region_name_slug):
   try:
      region = Region.objects.get(slug=region_name_slug)
   except Region.DoesNotExist:
      region = None
   
   form = CottageForm()
   if request.method == 'POST':
      form = CottageForm(request.POST)
      if form.is_valid():
         if region:
            cottage = form.save(commit=False)
            cottage.region = region
            cottage.views = 0
            cottage.save()
            return show_region(request, region_name_slug)
      else:
         print(form.errors)
         
   context_dict = {'form':form, 'region':region}      
   return render(request, 'dog/add_cottage.html', context_dict)


@login_required
def restricted(request):
   return render(request, 'dog/restricted.html', {})


#@login_required
#def user_logout(request):
#   logout(request)
#   return HttpResponseRedirect(reverse('index'))

def get_server_side_cookie(request, cookie, default_val=None):
      val = request.session.get(cookie)
      if not val:
         val = default_val
      return val

class MyRegistrationView(RegistrationView):
   def get_success_url(self, user):
      return '/dog/'


def visitor_cookie_handler(request):
      visits = int(request.COOKIES.get('visits', '1'))
      last_visit_cookie = request.COOKIES.get('last_visit', str(datetime.now()))
      last_visit_time = datetime.strptime(last_visit_cookie[:-7],
      '%Y-%m-%d %H:%M:%S')

      if (datetime.now() - last_visit_time).days > 0:
         visits = visits + 1
         request.session['last_visit'] = str(datetime.now())
      else:
         
         request.session['last_visit'] = last_visit_cookie

      request.session ['visits'] = visits

      
      

templates/dog/about.html
{% extends 'dog/base.html' %}

{% load staticfiles %}


{% load dog_template_tags %}
{% block title_block %}
  
About Us
{% endblock %}


{% block body_block %}


<h1>About us</h1>


{% block sidebar_block %}

{% get_region_list region %}

{% endblock %}

{% endblock %}

templates/dog/add_cottage.html
<!DOCTYPE html>
{% extends 'dog/base.html' %}
{% block title_block %} 
 Add a new page to {{ region.slug }} 
{% endblock %}
{%block body_block %}

	<h2> Add a new page to {{ region.slug }}</h2>
	
	<div><br />

		{% if not_region_name_url %}
			<div style="color: red;">The specified category doees not exist!</div> 
		{% else %}
		<form id="page_form" method="post" action="/dog/region/{{region.slug}}/add_cottage/">

		{% csrf_token %}	
		{% for hidden in form.hidden_fields %}
		{{ hidden }}
		{% endfor %}
		{% for field in form.visible_fields %}	
		{{ field.errors }}
		{{ field.help_text }}
		{{ field }} 
		{% endfor %}
		<input type="submit" name="submit" value="Add Cottage"/>
</form>
		
		{% endif %}
{% endblock %}	

templates/dog/add_region.html
<!DOCTYPE html>
{% extends 'dog/base.html' %}
{% load staticfiles %}

{% block title_block %} 
	Add a Region 
{% endblock %}
{% block body_block %}
	<h1> Add a Region</h1>	
	<div>
		<form id="region_form" method="post" action="/dog/add_region/">
		{% csrf_token %}	
		{% for hidden in form.hidden_fields %}
			{{ hidden }}
		{% endfor %}
		{% for field in form.visible_fields %}	
			{{ field.errors }}
			{{ field.help_text }}
			{{ field }} 
		{% endfor %}
		<input type="submit" name="submit" value="Create Region"/>
</form>
</div>
{% endblock %}	

templates/dog/base.html
<!DOCTYPE html>
{% load dog_template_tags %}
{% load staticfiles %}
<html lang="en">
  <head>

<title>
DOG BNB - 
{% block title_block %}
{% endblock %}
</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
     <!-- JQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

	<script type="text/javascript">
		
		$(document).ready(function(){
			// set the random image for the site background
			// only requires the relative path to the STATIC FILES folder
			var images = 10; // number of images
      // Get a random image from 1 to 10
			var randImage = Math.floor(Math.random() * images) + 1; 
      // Change the background image
			$(".background").css("background-image", "url('{% static "images/bg_" %}"+ randImage + ".jpg')");
		});
	</script>

	<style>
		body, html {
			height: 100%;
			margin: 0;
			font: 400 15px/1.8 "Myriad Pro", sans-serif;
			color: #777;
		}
		.background { 
			height: 100%;
			background-position: center;
			background-repeat: no-repeat;
			background-size: cover;
		
		}
		.container{
			border-radius: 15px;
			padding: 5%; 
		}
		.nav-item{
			color: white;
			}
		div.menu {
			width: 100%;
			margin-top: 0px;
			padding: 0px;	
			
		}
		div.footer {
			height:120px;
			margin: 10px auto 20px auto;
			padding: 0px;
			background: rgba(255, 255, 255, 0.8);
		}
		
		div.maincontent {
			margin-top: 7.5%;
			padding: 15px;
    			background: rgba(255, 255, 255, 0.8);
			
		}
		.navbar {
			padding: 15px;
			margin: 0px !important;

	
		}
		
		.button{
			border: none;
   			color: white;
    			padding: 5px;
    			text-align: center;
    			text-decoration: none;
    			display: inline-block;
   	 		font-size: 16px;
   			margin: 4px 2px;
    			-webkit-transition-duration: 0.4s; /* Safari */
   			transition-duration: 0.4s;
    			cursor: pointer;
			border-radius: 10px;
		}

		.searchbutton{
    			background-color: white;
    			color: black;
    			border: 2px solid #800000;
			//box-shadow: 1px 1px 11px #330033;
		}

		.searchbutton:hover {
    			background-color: #800000;
    			color: white;
		}
		.search{
			margin: 0px !important;
			float: left;
      			position: relative;
			padding-left: 10px;
			padding-right: 10px;	
		}
		.region{
    			position: relative;
		}
			
		#region{
			overflow:hidden;
			height: 7.5%; 
   			width: 20%; 
			-moz-border-radius: 9px 9px 9px 9px;
   			-webkit-border-radius: 9px 9px 9px 9px;
   			border-radius: 9px 9px 9px 9px;
   			//box-shadow: 1px 1px 11px #330033;
			background-color: white;
    			color: black;
    			border: 2px solid #800000;
		}
		#region:hover {
    			background-color: #800000;
    			color: white;
		}
		.input{
			background-color: white;
    			color: black;
    			border: 2px solid #800000;
			border-radius: 10px;
			//box-shadow: 1px 1px 11px #330033;
		}
		
	</style>

</head>
<body class='background'>

<!--- nav content area --> 
<div class="container menu">

<nav  id="navbar" class="navbar navbar-toggleable-md navbar-light bg-faded">

  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <a class="navbar-brand" href="/">
    <img src="https://v4-alpha.getbootstrap.com/assets/brand/bootstrap-solid.svg" width="30" height="30" alt="DOG BNB">
  </a>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'dog:about' %}">Regions</a>
      </li>


      {% if user.is_authenticated %}
	<li class="nav-item">
        <a class="nav-link" href="{% url 'dog:add_region' %}">Add Region</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'auth_logout' %}">Logout </a>
      </li>
	{% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'auth_login' %}">Login</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'registration_register' %}">Register </a>
      </li>

      {% endif %}

    </ul>

    <ul class="nav navbar-nav flex-row justify-content-between ml-auto">

    <li class="nav-item order-2 order-md-1"><a href="#" class="nav-link" title="settings"><i class="fa fa-cog fa-fw fa-lg"></i></a></li>

    <li class="dropdown order-1">

        <button type="button" id="dropdownMenu1" data-toggle="dropdown" class="btn btn-outline-secondary dropdown-toggle">Login <span class="caret"></span></button>

        <ul class="dropdown-menu dropdown-menu-right mt-1">

          <li class="p-3">

                <form class="form" role="form">

                    <div class="form-group">
                        <input id="emailInput" placeholder="Email" class="form-control form-control-sm" type="text" required="">
                    </div>
                    <div class="form-group">
                        <input id="passwordInput" placeholder="Password" class="form-control form-control-sm" type="text" required="">
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary btn-block">Login</button>
                    </div>
                    <div class="form-group text-xs-center">
                        <small><a href="#">Forgot password?</a></small>
                    </div>

                </form>

            </li>

        </ul>

    </li>
    </ul>

  </div>

</nav>
</div>

<div>

</div>


<!--- search bar 
<div class="container w3-display-container searchcontent">

  <form class="search w3-display-middle">

    <div >
	
	</div>
	</div>
    </div>



    <input class="button searchbutton" type="submit" value='Search'>


  </form>

</div>
-->

<!--- main content area -->
<div class="container w3-display-center maincontent">
{% block body_block %}
{% endblock %}
</div>

<!--- footer area
<div class="container footer">

</div> -->
<div class="container">
<center><p style='color: white; size:20px;'><em>Internet Technology Project by IT TAKES 4 TO DJANGO<em></p></center>
</div>

    <!-- jQuery first, then Tether, then Bootstrap JS. -->
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
  </body>
</html>

templates/dog/index.html
{% extends 'dog/base.html' %}
{% load staticfiles %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<style> 
		h1 {
		font-size: 250px;
		}
		.container{
			border-radius: 15px;
			padding: 5%; 
		}
		div.searchcontent {
			height:60px;
			margin-top: 10px;
			margin-left: auto;
    			margin-right: auto;	
			padding: 10px;
    			background: rgba(255, 255, 255, 0.8);
		}
		.search{
			float: left;
      			position: relative;
			padding-left: 10px;
			padding-right: 10px;	
		}
		.button{
			border: none;
   			color: white;
    			padding: auto;
    			text-align: center;
    			text-decoration: none;
   	 		font-size: 16px;
    			-webkit-transition-duration: 0.4s; /* Safari */
   			transition-duration: 0.4s;
    			cursor: pointer;
			border-radius: 10px;
		}

		.searchbutton{
    			background-color: white;
    			color: black;
    			border: 2px solid #483D8B;
			//box-shadow: 1px 1px 11px #330033;
		}

		.searchbutton:hover {
    			background-color: #483D8B;
    			color: white;
		}
		
		.region{
    			position: relative;
  			display: inline-block;
		}
			
		#region{
			overflow:hidden;
			height: 7.5%; 
   			width: 40%; 
			-moz-border-radius: 9px 9px 9px 9px;
   			-webkit-border-radius: 9px 9px 9px 9px;
   			border-radius: 9px 9px 9px 9px;
   			//box-shadow: 1px 1px 11px #330033;
			background-color: white;
    			color: black;
    			border: 2px solid #483D8B;
		}
		#region:hover {
    			background-color: #483D8B;
    			color: white;
		}
		.input{
			background-color: white;
    			color: black;
    			border: 2px solid #483D8B;
			border-radius: 10px;
			//box-shadow: 1px 1px 11px #330033;
		}
		
</style>
{% block title_block %}
  Homepage
{% endblock %}
{% block body_block %}

<div class="w3-display-container">
<h1 style="color: white" class="w3-display-middle"> Dogbnb </h1> 
</div>

<!--- search bar -->
<div class="container w3-display-container searchcontent">

  <form class="search w3-display-middle">

    <select id="region" class="button">
	<option>--select region</option>
	<option value='region1'>Region 1</option>
    	<option value='region2'>Region 2</option>
	</div>
	</div>
    </select>

    <input class="input" type="text" name="price_from">
    <input class="input" type="text" name="price_to">
    <input class="button searchbutton " type="submit" value='Search'>


  </form>

</div>

{% endblock %}

templates/dog/region.html
<!DOCTYPE html>
{% extends 'dog/base.html' %}
{% load staticfiles %}

{% block title_block %}
	{{ region.name }}
{% endblock %}

{% block body_block %}
	{% if region %}
		<h1>{{ region.name }}</h1>
		
		{% if cottages %}
			<ul>
			{% for cottage in cottages %}
 				<li>{{ cottage.address }}>{{ cottage.title }} </a></li>
			{% endfor %}
			</ul>
		{% else %}
			<strong>No cottages currently in region.</strong>
		{% endif %}
		
		{% if user.is_authenticated %}
			<a href="{% url 'dog:add_cottage' region.slug %}">Add a Cottage</a>
		{% endif %}
	{% else %}
		The specified Region does not exist!
	{% endif %}
{% endblock %} 

templates/dog/regs.html
<ul>
{% if regs %}
	{% for r in regs %}
		{% if r == act_reg %}
			<li>
			<strong>
			<a href="{% url 'dog:show_region' r.slug %}">{{ r.name }}</a>
			</strong>	
			</li>
		{% else %}
			<li>
			<a href="{% url 'dog:show_region' r.slug %}">{{ r.name }}</a>
			</li>
		{% endif %}
	{% endfor %}
{% endif %}
</ul>

templates/dog/restricted.html
<!DOCTYPE html>
{% extends 'rango/base.html' %}

{% load staticfiles %}

{% block title_block %}
	Restricted
{% endblock %}

{% block body_block %}
	
	<div>
		<h1>Restricted Page! </h1>
	 
		Since you're logged in, you can see this text!
	
	</div>

{% endblock %}

templates/dog/search-results.html
{% extends 'dog/base.html' %}
{% load staticfiles %}

{% block title_block %}
  Search results
{% endblock %}

{% block body_block %}

	<h1>Search Results</h1>
	<p>Results placeholder</p>

	
{% endblock %}